=== Sliwson/cuda-slam/config/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "type": "object",
  "required": [ "before-path", "after-path", "method" ],
  "properties": {
    "before-path": {
      "type": "string"
    },
    "after-path": {
      "type": "string"
    },
    "method": {
      "type": "string",
      "enum": [ "icp", "nicp", "cpd" ]
    },
    "policy": {
      "type": "string",
      "enum": [ "sequential", "parallel" ]
    },
    "translation": {
      "type": "array",
      "minLength": 3,
      "maxLength": 3,
      "items": {
        "type": "number"
      }
    },
    "rotation": {
      "type": "array",
      "minLength": 9,
      "maxLength": 9,
      "items": {
        "type": "number"
      }
    },
    "translation-range": {
      "type": "number"
    },
    "angle-range": {
      "type": "number"
    },
    "max-iterations": {
      "type": "integer"
    },
    "cloud-resize": {
      "type": "integer"
    },
    "show-visualisation": {
      "type":  "boolean"
    }
  }
}

=== Sliwson/cuda-slam/config/default.json
{
  "before-path": "data/bunny.obj",
  "after-path": "data/bunny.obj",
  "method": "icp",
  "policy": "parallel",
  "translation": [ 1.0, 1.0, 1.0 ],
  "rotation": [
    0.3062,
    0.9186,
    0.2500,
    0.8839,
    0.1768,
    0.4330,
    0.3536,
    0.3536,
    0.8660
  ],
  "show-visualisation":  true
}
